name: Build iOS Development Client

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js
    - name: ðŸ— Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install -g expo-cli eas-cli

### Build the Android App
# Set up EAS
    - name: ðŸ— Setup EAS
      uses: expo/expo-github-action@v8
      with:
          eas-version: latest
          token: ${{ secrets.EXP0_TOKEN }}

# Build the Android app
    - name: Build Android app
      run: |
        eas build --platform android --non-interactive

# Upload APK artifact
    - name: Upload Android build artifact
      uses: actions/upload-artifact@v3
      with:
       name: android-build
       path: ./builds/*-release.apk
  
### Build the iOS App

 # create eas.json file with development profile for IOS
    - name: Create eas.json file
      run: |
            echo '{
            "build": {
                "development": {
                "ios": {
                    "buildType": "simulator"
                }
                }
            }
            }' > eas.json

    # Build iOS Development Client
    - name: Build iOS Client
      env:
        EAS_BUILD_PROFILE: development
      run: |
        eas build --platform ios --profile development --non-interactive

    # Upload the build artifact (optional)
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: ./build
